---
- name: hello world
  hosts: localhost

  tasks:
    - include_vars: vars_sept.yaml
    - name: display hello world
      shell: echo "hello world"
      register: contents
      tags:
        - nodes

    - name: display hi
      shell: echo "{{webservers}}"
      

    - name: run date
      command: date
      tags:
        - nodes

    - name: list file contents
      command: cat resolv.conf
      args:
        chdir: /etc

    - name: add server to file
      lineinfile:
        path: test.txt
        line: 'server {{ip_address}}'

    - name: create user "{{ item }}"
      shell: echo 'name = "{{ item }}"'
      loop:
        - Conrad
        - Gunjan
        - IBT
        - Vibes

    - name: installing '{{ item.name }}'
      shell: echo 'name = {{ item.name }}'
      when: item.required == true
      loop: '{{ softwares }}'
    
    - name: run command if task1 is successful
      command: echo "success"
      when: contents.stdout.find('hello world')!= -1

    - name: gather facts
      debug:
        var: ansible_facts