---
- name: show facts and run some conditions
  hosts: localhost

  tasks:
   - name: show ansible facts
     debug:
      var: ansible_facts

   - name: run command on basis of facts
     command: echo "os family ia Ubuntu"
     when: ansible_facts['os_family'] == 'Darwin'

