---
- name: Play 1
  hosts: localhost
  vars:
    day: 6th May
    test: data

  tasks:
    - name: helloworld
      shell: echo "hello world"

    - name: hi
      shell: echo "hi"

    - name: date
      command: date

    #- name: run a script
    #  script: test.sh

    - name: display contents of a file
      command: cat resolv.conf chdir=/etc

    - name: add line in file
      lineinfile:
          path: test.sh
          line: 'day - {{ day }}'

    - name: add line in file
      lineinfile:
        path: test.sh
        line: '{{ test }}'


